# Generated by Django 4.2.1 on 2023-10-18 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barangayApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_2', models.BigIntegerField(null=True)),
                ('name', models.CharField(max_length=75, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_2', models.CharField(max_length=75, null=True)),
                ('id_3', models.BigIntegerField(null=True)),
                ('name', models.CharField(max_length=75, null=True)),
                ('municipal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barangayApp.municipal')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
