# Generated by Django 4.2.1 on 2023-10-18 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barangayApp', '0002_municipal_barangay'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='barangay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='barangayApp.barangay'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='municipal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='barangayApp.municipal'),
        ),
    ]
