# Generated by Django 4.2.1 on 2023-10-18 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barangayApp', '0006_barangay_municipal'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(default=11.5833)),
                ('longitude', models.FloatField(default=124.4642)),
                ('photo', models.ImageField(default='path/to/default/FB_IMG_1692936618339.jpg', upload_to='tourist_spot_photos/')),
                ('spot_type', models.CharField(choices=[('Natural', 'Natural Attraction'), ('Historical', 'Historical/Cultural Site'), ('Adventure', 'Adventure/Outdoor Activity'), ('Recreational', 'Recreational/Relaxation Spot'), ('Educational', 'Educational Institution'), ('Culinary', 'Food/Culinary Spot'), ('Scenic', 'Scenic View/Lookout Point'), ('Festival', 'Festival/Event')], default='Natural', max_length=20)),
                ('municipal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barangayApp.municipal')),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('suffix', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True)),
                ('vaccination', models.CharField(blank=True, choices=[('Vaccinated', 'Vaccinated'), ('Not Vaccinated', 'Not Vaccinated')], max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Annuled', 'Annuled'), ('Widowed', 'Widowed'), ('Separated', 'Separated'), ('Common Law/Live-in', 'Common Law/Live-in'), ('Unknown', 'Unknown')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('barangay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barangayApp.barangay')),
                ('municipal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barangayApp.municipal')),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_senior_citizens', models.IntegerField(null=True)),
                ('num_pregnant_lactating_mothers', models.IntegerField(null=True)),
                ('num_beneficiaries_with_disability', models.IntegerField(null=True)),
                ('relationship', models.CharField(blank=True, choices=[('Spouse', 'Spouse'), ('Partner', 'Partner'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Father', 'Father'), ('Mother', 'Mother'), ('Mother in Law', 'Mother in Law'), ('Father in Law', 'Father in Law'), ('Stepson', 'Stepson'), ('Stepdaughter', 'Stepdaughter'), ('Son in Law', 'Son in Law'), ('Daughter in Law', 'Daughter in Law'), ('Brother in Law', 'Brother in Law'), ('Sister in Law', 'Sister in Law'), ('Uncle', 'Uncle'), ('Aunt', 'Aunt'), ('Nephew', 'Nephew'), ('Niece', 'Niece'), ('Boarder', 'Boarder'), ('Domestic Helper', 'Domestic Helper'), ('Nonrelative', 'Nonrelative'), ('Other Relative', 'Other Relative')], max_length=50, null=True)),
                ('latitude', models.FloatField(default=11.5833)),
                ('longitude', models.FloatField(default=124.4642)),
                ('barangay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barangayApp.barangay')),
                ('beneficiaries', models.ManyToManyField(related_name='households', to='barangayApp.resident')),
                ('household_head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_of_household', to='barangayApp.resident')),
                ('municipal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barangayApp.municipal')),
            ],
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateField()),
                ('disability', models.CharField(choices=[('Visual Disability', 'Visual Disability'), ('Hearing Disability', 'Hearing Disability'), ('Intellectual Disability', 'Intellectual Disability'), ('Learning Disability', 'Learning Disability'), ('Mental Disability', 'Mental Disability'), ('Physical Disability', 'Physical Disability'), ('Psychosocial Disability', 'Psychosocial Disability'), ('Speech and Language Impairment', 'Speech and Language Impairment')], max_length=50, null=True)),
                ('illness', models.CharField(choices=[('Diabetes', 'Diabetes'), ('Cancer', 'Cancer'), ('Hypertension', 'Hypertension'), ('Tuberculosis (TB)', 'Tuberculosis (TB)'), ('Acute Respiratory Infection', 'Acute Respiratory Infection'), ('Acute Gastroenteritis', 'Acute Gastroenteritis'), ('Common Colds, Cough, Flu/Fever', 'Common Colds, Cough, Flu/Fever'), ('Cut/Wound', 'Cut/Wound'), ('Burn', 'Burn'), ('Fracture', 'Fracture'), ('Dislocation', 'Dislocation'), ('Surgical Illness', 'Surgical Illness'), ('Covid-19', 'Covid-19')], max_length=50, null=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barangayApp.resident')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('early_childhood_education', models.CharField(choices=[('No Grade Completed', 'No Grade Completed'), ('Nursery', 'Nursery'), ('Kindergarten', 'Kindergarten')], max_length=50, null=True)),
                ('primary_education', models.CharField(choices=[('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2 '), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 6', 'Grade 5'), ('Grade 6', 'Grade 6')], max_length=50, null=True)),
                ('lower_secondary_education', models.CharField(choices=[('Grade 7 / 1st year highschool', 'Grade 7 / 1st year highschool'), ('Grade 8 / 2nd year highschool', 'Grade 7 / 2nd year highschool'), ('Grade 9 / 3rd year highschool', 'Grade 7 / 3rd year highschool'), ('Grade 10 / 4th year highschool', 'Grade 7 / 4th year highschool')], max_length=50, null=True)),
                ('upper_secondary_education', models.CharField(choices=[('Grade 11', 'Grade 11'), ('Grade 12', 'Grade 12')], max_length=50, null=True)),
                ('bachelor_education', models.CharField(choices=[('1st Year College', '1st Year College'), ('2nd Year College', '2nd Year College'), ('3rd Year College ', '3rd Year College '), ('4th Year College', '4th Year College')], max_length=50, null=True)),
                ('master_doctoral_education', models.CharField(choices=[('Undergraduate', 'Undergraduate')], max_length=50, null=True)),
                ('curriculum_strands', models.CharField(choices=[('General Academic Strand', 'General Academic Strand'), ('Science Technology Engineering and Mathematics', 'Science Technology Engineering and Mathematics'), ('Humanities and Social Sciences', 'Humanities and Social Sciences'), ('Sports Track', 'Sports Track'), ('Arts and Design', 'Arts and Design'), ('Technology and Livelihood Education and Technical - Vocational Livelihood', 'Technology and Livelihood Education and Technical - Vocational Livelihood')], max_length=150, null=True)),
                ('undergraduate_reason', models.CharField(choices=[('Illness', 'Illness'), ('Accessibility of School', 'Accessibility of School'), ('Disability', 'Disability'), ('Pregnancy', 'Pregnancy'), ('Marriage', 'Marriage'), ('High Cost of Education / Financial Concern', 'High Cost of Education / Financial Concern'), ('Employment', 'Employment'), ('Finished Schooling', 'Finished Schooling'), ('Looking For Work', 'Looking For Work'), ('Lack of Personal Interest', 'Lack of Personal Interest'), ('Too young to go to School', 'Too young to go to School'), ('Bullying', 'Bullying'), ('Family Matters', 'Family Matters')], max_length=150, null=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barangayApp.resident')),
            ],
        ),
        migrations.CreateModel(
            name='Economic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_occupation', models.CharField(max_length=50, null=True)),
                ('industry_of_work', models.CharField(max_length=50, null=True)),
                ('working_arrangement', models.CharField(choices=[('Default Place of Work', 'Default Place of Work'), ('Work From Home', 'Work From Home'), ('Home-based Work', 'Home-based Work'), ('On Job Rotation', 'On Job Rotation'), ('On a Mixed Arrangement', 'On a Mixed Arrangement'), ('On Reduced Hours', 'On Reduced Hours')], max_length=50, null=True)),
                ('nature_of_employment', models.CharField(choices=[('Permanent Job/Business', 'Permanent Job/Business'), ('Short Term/Seasonal Job', 'Short Term/Seasonal Job'), ('Worked for Different Employers', 'Worked for Different Employers')], max_length=50, null=True)),
                ('class_of_worker', models.CharField(choices=[('Private Household', 'Private Household'), ('Private Establishment', 'Private Establishment'), ('Government/Corporation', 'Government/Corporation'), ('Self - Employed', 'Self - Employed'), ('Employer', 'Employer'), ('Family Operated Business', 'Family Operated Business')], max_length=50, null=True)),
                ('basis_of_payment', models.CharField(choices=[('Imputed Salary ', 'Imputed Salary'), ('Per Piece', 'Per Piece'), ('Per Hour', 'Per Hour'), ('Per Day', 'Per Day'), ('Monthly', 'Monthly'), ('Weekly', 'Weekly')], max_length=50, null=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barangayApp.resident')),
            ],
        ),
    ]
