# Generated by Django 4.2.1 on 2023-10-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangayApp', '0007_touristspot_resident_household_health_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='num_members_per_households',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='num_registered_voters',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='economic',
            name='class_of_worker',
            field=models.CharField(choices=[('Private Household', 'Private Household'), ('Private Establishment', 'Private Establishment'), ('Government/Corporation', 'Government/Corporation'), ('Self - Employed', 'Self - Employed'), ('Unemployed', 'Unemployed'), ('Employer', 'Employer'), ('Family Operated Business', 'Family Operated Business')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='economic',
            name='working_arrangement',
            field=models.CharField(choices=[('Work From Home', 'Work From Home'), ('Home-based Work', 'Home-based Work'), ('On Job Rotation', 'On Job Rotation'), ('On a Mixed Arrangement', 'On a Mixed Arrangement'), ('On Reduced Hours', 'On Reduced Hours')], max_length=50, null=True),
        ),
    ]
