# Generated by Django 4.2.1 on 2023-10-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangayApp', '0009_rename_beneficiaries_household_members_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='languages_spoken',
        ),
        migrations.RemoveField(
            model_name='household',
            name='occupation_of_members',
        ),
        migrations.RemoveField(
            model_name='household',
            name='special_needs',
        ),
        migrations.AlterField(
            model_name='household',
            name='access_to_basic_amenities',
            field=models.TextField(blank=True, choices=[('Electricity', 'Electricity'), ('Clean Water', 'Clean Water'), ('Sanitation', 'Sanitation'), ('Housing', 'Housing'), ('Health Services', 'Health Services'), ('Education', 'Education'), ('Communication', 'Communication'), ('Transportation', 'Transportation'), ('Others', 'Others')], null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='education_level_of_head',
            field=models.CharField(blank=True, choices=[('No Formal Education', 'No Formal Education'), ('Elementary School', 'Elementary School'), ('High School Graduate', 'High School Graduate'), ('College Graduate', 'College Graduate'), ('Postgraduate Degree', 'Postgraduate Degree')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='household_type',
            field=models.CharField(blank=True, choices=[('Nuclear Family', 'Nuclear Family'), ('Extended Family', 'Extended Family'), ('Single Parent Family', 'Single Parent Family'), ('Child-Headed Family', 'Child-Headed Family'), ('Elderly-Headed Family', 'Elderly-Headed Family'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='housing_condition',
            field=models.CharField(blank=True, choices=[('Owned', 'Owned'), ('Rented', 'Rented'), ('Government Housing', 'Government Housing'), ('Informal Settlement', 'Informal Settlement'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='monthly_income_range',
            field=models.CharField(blank=True, choices=[('Less than ₱10,000', 'Less than ₱10,000'), ('₱10,000 - ₱20,000', '₱10,000 - ₱20,000'), ('₱20,000 - ₱30,000', '₱20,000 - ₱30,000'), ('₱30,000 - ₱40,000', '₱30,000 - ₱40,000'), ('More than ₱40,000', 'More than ₱40,000')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='ownership_of_assets',
            field=models.TextField(blank=True, choices=[('Land', 'Land'), ('House', 'House'), ('Vehicle', 'Vehicle'), ('Livestock', 'Livestock'), ('Appliances', 'Appliances'), ('Savings', 'Savings'), ('Business', 'Business'), ('Other Assets', 'Other Assets')], null=True),
        ),
    ]
