# Generated by Django 4.2.1 on 2023-11-01 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barangayApp', '0010_remove_household_languages_spoken_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resident',
            options={'ordering': ['last_name']},
        ),
    ]
