# Generated by Django 4.2.1 on 2023-11-14 06:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('barangayApp', '0011_alter_resident_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economic',
            name='basis_of_payment',
            field=models.CharField(choices=[('Imputed Salary', 'Imputed Salary'), ('Per Piece', 'Per Piece'), ('Per Hour', 'Per Hour'), ('Per Day', 'Per Day'), ('Monthly', 'Monthly'), ('Weekly', 'Weekly')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barangayApp.resident')),
            ],
        ),
    ]
