# Generated by Django 4.2.1 on 2023-11-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangayApp', '0016_address_touristspot_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['username'], 'permissions': [('can_view_super_admin_views', 'Can view super admin views'), ('can_view_provincial_admin_views', 'Can view provincial admin views'), ('can_view_municipal_admin_views', 'Can view municipal admin views'), ('can_view_municipal_staff_views', 'Can view municipal staff views'), ('can_view_barangay_admin_views', 'Can view barangay admin views'), ('can_view_barangay_staff_views', 'Can view barangay staff views'), ('can_view_tourist_staff_views', 'Can view tourist staff views')]},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('provincial_admin', 'Provincial Admin'), ('municipal_admin', 'Municipal Admin'), ('barangay_admin', 'Barangay Admin'), ('barangay_staff', 'Barangay Staff'), ('tourist_staff', 'Tourist Officer')], max_length=50),
        ),
    ]
