# Generated by Django 4.2.1 on 2023-11-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangayApp', '0017_alter_customuser_options_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='provincial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
