# Generated by Django 4.2.1 on 2023-11-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangayApp', '0018_customuser_provincial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='provincial',
            field=models.CharField(default='Biliran', max_length=50),
        ),
    ]
