# Generated by Django 4.2.1 on 2023-11-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangayApp', '0021_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='document_type',
            field=models.CharField(blank=True, choices=[('barangay_clearance', 'Barangay Clearance'), ('certificate_of_indigency', 'Certificate of Indigency')], max_length=50, null=True),
        ),
    ]
