# Generated by Django 4.2.1 on 2023-11-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangayApp', '0022_transaction_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='health',
            name='malnutrition_status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='pregnancy_status',
            field=models.CharField(choices=[('Pregnant', 'Pregnant'), ('Not Pregnant', 'Not Pregnant'), ('Prefer not to say', 'Prefer not to say')], max_length=50, null=True),
        ),
    ]
