# Generated by Django 4.2.1 on 2023-11-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangayApp', '0023_health_malnutrition_status_health_pregnancy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='malnutrition_status',
            field=models.CharField(choices=[('Severe malnutrition', 'Severe malnutrition'), ('Moderate malnutrition', 'Moderate malnutrition'), ('Mild malnutrition', 'Mild malnutrition'), ('No malnutrition', 'No malnutrition')], max_length=50, null=True),
        ),
    ]
